# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Antonucci
description: > # this means to ignore newlines until "baseurl:"
  Journalist turned full-time coder, part-time ponderer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.maxwellantonucci.com" # the base hostname & protocol for your site
author: Max Antonucci
plugins: [jekyll-paginate-v2]

svg_color: "#38A89D"

pagination:
  enabled: true
  sort_field: date
  permalink: '/:num/'
  sort_reverse: true
  per_page: 15
  trail:
    before: 2
    after: 2

exclude: [
  'node_modules'
]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  notes:
    output: true

feed:
  path: rss.xml
  collections:
    - notes

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      postLabel: "Blog Post"
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "page"
      excerpt: ""
      postLabel: "Note"
