name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # At 06:00
    - cron: 0 8 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
